### ISSUE TITLE
Explicitly conform to the numpydoc docstring guide

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-python#12]
The [numpydoc docstring guide](https://numpydoc.readthedocs.io/en/latest/format.html) seems to be compatible with Sphinx, and to build upon [reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html).

**Comment by kmcelwee** [comment]
We've decided to centralize documentation in dspace-development
