### ISSUE TITLE
Request updates for the Restrictions Spreadsheet export

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-python#27]
It would be preferred to have a unique ID (such as the student ID or e-mail address) provided in the Restrictions Spreadsheet export. This would need to be requested from Lynn Durgin for supporting future exports.

**Comment by kmcelwee** [comment]
Some pushback on developers up the data pipeline. Instead of advocating that they add the field, the restrictions script will attempt to match by name, then department, then thesis title, and if there is still some kind of problem, it will then throw an error.
