### ISSUE TITLE
Document the process for automating the ingestion of PPPL data sets into DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-python#32]
@jrgriffiniii commented on [Mon May 04 2020](https://github.com/pulibrary/dspace-cli/issues/10)

Currently the Princeton Plasma Physics Laboratory (PPPL) provides a synchronous process by which DSpace submission information packages are structured and uploaded to an Amazon S3 Bucket. DataSpace uses a cron task in order to parse the entries of the S3 Bucket nightly for new deposits, and when it finds these, ingests them as new DSpace Items.

**Comment by kmcelwee** [comment]
This ticket is now obsolete 🎉
