### ISSUE TITLE
Ensure that there is support for the Python releases 2.7.5 and 3.8.3

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-python#7]
Currently, I have found the following Python versions supported here:

- dataspace: 2.7.5
- oar: 2.7.5
- updatespace: 2.7.5

**Comment by jrgriffiniii** [comment]
I assumed that defaulting to Python 3.x support would be preferred, as this would permit one to backport functionality for operation system environments relying upon Python 2.7.x releases.

**Comment by kmcelwee** [comment]
In the past year, any python scripts have been executed on local environments
