### ISSUE TITLE
Thesis Central script support for CSV

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-python#8]
Currently this assumes that one should be working with Excel Spreadsheets (please see https://github.com/pulibrary/dspace-python/blob/master/thesiscentral-vireo/dataspace/python/vireo.py#L22) - should this be the case? Perhaps we should be parsing CSV files.

**Comment by kmcelwee** [comment]
Made redundant by PR #17 and Issue #16
